Repository swe574-Fall2024-Group1/huddleup, pull requests merged in 2024-11, with the labels that each got.

#55 Feature/mobile UI
  huddleupui/public/index.html
  huddleupui/public/logo192.png
  huddleupui/public/logo512.png
  huddleupui/public/manifest.json
  huddleupui/public/serviceWorker.js
  huddleupui/src/components/MainLayout/LeftSidebar.jsx
  huddleupui/src/components/MainLayout/Navbar.jsx
  huddleupui/src/components/MainLayout/RighSidebar.jsx
  huddleupui/src/layouts/CommunityLayout.jsx
  huddleupui/src/layouts/MainLayout.jsx
  huddleupui/src/pages/Login.jsx
  huddleupui/src/pages/Register.jsx
  huddleupui/src/pages/UserFeed.jsx
Labels: enhancement, frontend, mobile

#63 Feature/ci pipeline unit tests
  .env.sample
  .github/workflows/ci-test.yaml
Labels: Infra & DevOps

#68 Feature: adding tags to posts and users
  huddleupAPI/authAPI/class_views.py
  huddleupAPI/authAPI/migrations/0003_user_tags.py
  huddleupAPI/authAPI/models.py
  huddleupAPI/authAPI/serializers.py
  huddleupAPI/authAPI/urls.py
  huddleupAPI/authAPI/views.py
  huddleupAPI/communityAPI/admin.py
  huddleupAPI/communityAPI/class_views.py
  huddleupAPI/communityAPI/migrations/0002_post_tags.py
  huddleupAPI/communityAPI/models.py
  huddleupAPI/communityAPI/serializers.py
  huddleupAPI/communityAPI/tests.py
  huddleupAPI/communityAPI/urls.py
  huddleupAPI/communityAPI/views.py
  huddleupAPI/huddleupAPI/settings.py
  huddleupAPI/requirements.txt
  huddleupui/package-lock.json
  huddleupui/package.json
  huddleupui/src/App.js
  huddleupui/src/components/Auth/AuthProvider.jsx
  huddleupui/src/components/Community/Post.js
  huddleupui/src/components/MainLayout/Navbar.jsx
  huddleupui/src/index.js
  huddleupui/src/pages/Community/CreatePost.jsx
  huddleupui/src/pages/Community/EditPost.jsx
  huddleupui/src/pages/UserProfile.jsx
Labels: backend, frontend

#72 Feature/cd pipeline
  .github/workflows/cd.yaml
  docker-compose.yaml
Labels: Infra & DevOps
